In [1]:
import pandas as pd

In [10]:
info= {
    "Name" :["Sunil","Ankit","Swatik"],
    "CGPA" :[7.5,9.3,7.9]
}

df=pd.DataFrame(info)
print(df)

     Name  CGPA
0   Sunil   7.5
1   Ankit   9.3
2  Swatik   7.9

In [11]:
df

     Name  CGPA
0   Sunil   7.5
1   Ankit   9.3
2  Swatik   7.9

In [16]:
s=pd.Series([1,2,3,4,5,6,7,8,9])
print(s)
print(type(s))

#index
print(s[0])
print(s[5])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
<class 'pandas.core.series.Series'>
1
6

In [21]:
s=pd.Series([25,26,27,35] , index=["Sunil","Ankit","Som","Joga"])
print(s)

print(s["Sunil"])

Sunil    25
Ankit    26
Som      27
Joga     35
dtype: int64
25

In [24]:
s1=pd.Series([25,26,27,35,45])
s2=pd.Series([22,34,54,65,76])

print(s1+s2)
print(type(s1))

0     47
1     60
2     81
3    100
4    121
dtype: int64
<class 'pandas.core.series.Series'>

In [35]:
info= {
    "Name" :["Sunil","Ankit","Swatik"],
    "CGPA" :[7.5,9.3,7.9],
    "Age"  : [24,13,45]
}

df=pd.DataFrame(info)


print(df,(type(df)))
print(df.index)
print(df.columns)

     Name  CGPA  Age
0   Sunil   7.5   24
1   Ankit   9.3   13
2  Swatik   7.9   45 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='object')

In [34]:
df

     Name  CGPA  Age
0   Sunil   7.5   24
1   Ankit   9.3   13
2  Swatik   7.9   45

In [41]:
df=pd.DataFrame([["Sunil" ,24],["Som",26],["Sai",29]] , columns=["Name","Age"])
print(df)

    Name  Age
0  Sunil   24
1    Som   26
2    Sai   29