In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("product_reviews_raw.csv")

In [4]:
#Mising values
df["category"] = df["category"].fillna("Unknown")
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])
df["review_text"] = df["review_text"].fillna("No Review")
df["reviewer_name"] = df["reviewer_name"].fillna("No Name")
df["review_date"] = df["review_date"].fillna("No Date")
df["verified_purchase"] = df["verified_purchase"].fillna("Unknown")
df["helpful_votes"] = df["helpful_votes"].fillna("0")

In [5]:
#Duplicated values
df[["reviewer_name","review_date"]].duplicated()

df.drop_duplicates()

,review_id,product_name,category,rating,review_text,reviewer_name,review_date,verified_purchase,helpful_votes,price_usd
0,1062,Running Shoes Men's,Sports&Outdoors,2,"Do not buy this Running Shoes, total waste o...",Sofia S.,24-12-2023,No,1.0,64.99
1,1113,Wireless Mouse Ergonomic,Electronic,2,"Very disappointed with this Wireless Mouse, br...",raj l.,10/02/2023,No,2.0,16.99
2,1074,Yoga Mat Non-Slip,Sports & Outdoors,5,BEST YOGA MAT I'VE PURCHASED IN YEARS. 5 STARS.,Fatima N.,2024-04-13,1,2.0,24.99
3,1180,Wireless Mouse Ergonomic,ELECTRONICS,3,"Wireless Mouse works fine so far, will update ...",Grace T.,11/05/2024,No,2.0,16.99
4,1075,Resistance Bands Set,Sports&Outdoors,5,This Resistance Bands exceeded my expectations...,Maria L.,"March 26, 2024",No,3.0,15.99
...,...,...,...,...,...,...,...,...,...,...
193,1159,Memory Foam Pillow,Home and Kitchen,2,"Poor quality Memory Foam, would not recommen...",Wei S.,2023-04-13,Yes,3.0,29.99
194,1052,Kitchen Knife Set,Home&Kitchen,1,"Do not buy this Kitchen Knife, total waste of ...",Maria B.,08/23/2024,Unknown,0.0,39.99
195,1065,Dumbbell Set Adjustable,Sports & Outdoors,3,"Dumbbell Set works fine so far, will update re...",Mei P.,"October 17, 2023",Yes,0,89.99
198,1014,hiking backpack 40l,sports & outdoors,3,"It's a decent Hiking Backpack for the price, s...",Fatima S.,21-07-2024,No,0.0,58.99
199,1142,Cast Iron Skillet 12-inch,Home & kitchen,4,"Excellent quality Cast Iron, my whole family...",John R.,05/14/2023,FALSE,2.0,42.00

In [6]:
df.dtypes

review_id             int64
product_name         object
category             object
rating               object
review_text          object
reviewer_name        object
review_date          object
verified_purchase    object
helpful_votes        object
price_usd            object
dtype: object

In [13]:

df["review_date"] = pd.to_date

0    24/12/2023
1           NaN
2           NaN
3           NaN
4           NaN
Name: review_date, dtype: object

/var/folders/z0/fvcl60f96wg5nf_gfnp2x6j80000gn/T/ipykernel_7918/241072092.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["review_date"] = pd.to_datetime(df["review_date"], errors="coerce")

In [36]:
df["product_name"] = df["product_name"].str.upper()
df["category"] = df["category"].str.upper()
df["review_text"] = df["review_text"].str.upper()

In [29]:
#df["category"].str.upper()

0          SPORTS&OUTDOORS
1               ELECTRONIC
2        SPORTS & OUTDOORS
3              ELECTRONICS
4          SPORTS&OUTDOORS
              ...
195      SPORTS & OUTDOORS
196    SPORTS AND OUTDOORS
197      SPORTS & OUTDOORS
198      SPORTS & OUTDOORS
199         HOME & KITCHEN
Name: category, Length: 200, dtype: object

In [37]:
df

,review_id,product_name,category,rating,review_text,reviewer_name,review_date,verified_purchase,helpful_votes,price_usd
0,1062,RUNNING SHOES MEN'S,SPORTS&OUTDOORS,2,"DO NOT BUY THIS RUNNING SHOES, TOTAL WASTE O...",Sofia S.,24/12/2023,No,1.0,64.99
1,1113,WIRELESS MOUSE ERGONOMIC,ELECTRONIC,2,"VERY DISAPPOINTED WITH THIS WIRELESS MOUSE, BR...",raj l.,NaN,No,2.0,16.99
2,1074,YOGA MAT NON-SLIP,SPORTS & OUTDOORS,5,BEST YOGA MAT I'VE PURCHASED IN YEARS. 5 STARS.,Fatima N.,NaN,1,2.0,24.99
3,1180,WIRELESS MOUSE ERGONOMIC,ELECTRONICS,3,"WIRELESS MOUSE WORKS FINE SO FAR, WILL UPDATE ...",Grace T.,NaN,No,2.0,16.99
4,1075,RESISTANCE BANDS SET,SPORTS&OUTDOORS,5,THIS RESISTANCE BANDS EXCEEDED MY EXPECTATIONS...,Maria L.,NaN,No,3.0,15.99
...,...,...,...,...,...,...,...,...,...,...
195,1065,DUMBBELL SET ADJUSTABLE,SPORTS & OUTDOORS,3,"DUMBBELL SET WORKS FINE SO FAR, WILL UPDATE RE...",Mei P.,NaN,Yes,0,89.99
196,1006,HIKING BACKPACK 40L,SPORTS AND OUTDOORS,4,"EXCELLENT QUALITY HIKING BACKPACK, MY WHOLE FA...",James S.,02/10/2024,Yes,0.0,58.99
197,1004,HIKING BACKPACK 40L,SPORTS & OUTDOORS,4,"EXCELLENT QUALITY HIKING BACKPACK, MY WHOLE FA...",Grace T.,NaN,Yes,0.0,$58.99
198,1014,HIKING BACKPACK 40L,SPORTS & OUTDOORS,3,"IT'S A DECENT HIKING BACKPACK FOR THE PRICE, S...",Fatima S.,21/07/2024,No,0.0,58.99
199,1142,CAST IRON SKILLET 12-INCH,HOME & KITCHEN,4,"EXCELLENT QUALITY CAST IRON, MY WHOLE FAMILY...",John R.,NaN,FALSE,2.0,42.00

In [34]:
df["reviewer_name"].str.split(" ")

0       [Sofia, S.]
1         [raj, l.]
2      [Fatima, N.]
3       [Grace, T.]
4       [Maria, L.]
           ...
195       [Mei, P.]
196     [James, S.]
197     [Grace, T.]
198    [Fatima, S.]
199      [John, R.]
Name: reviewer_name, Length: 200, dtype: object

In [38]:
df2

NameError: name 'df2' is not defined