In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("product_reviews_raw.csv")

In [3]:
#Mising values
df["category"] = df["category"].fillna("Unknown")
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])
df["review_text"] = df["review_text"].fillna("No Review")
df["reviewer_name"] = df["reviewer_name"].fillna("No Name")
df["review_date"] = df["review_date"].fillna("No Date")
df["verified_purchase"] = df["verified_purchase"].fillna("Unknown")
df["helpful_votes"] = df["helpful_votes"].fillna("0")

In [26]:
#Duplicated values
df[["reviewer_name"]].duplicated()

df.drop_duplicates()

,review_id,product_name,category,rating,review_text,reviewer_name,review_date,verified_purchase,helpful_votes,price_usd
0,1062,RUNNING SHOES MEN'S,SPORTS&OUTDOORS,2,"DO NOT BUY THIS RUNNING SHOES, TOTAL WASTE O...",Sofia s.,24/12/2023,No,1.0,64.99
1,1113,WIRELESS MOUSE ERGONOMIC,ELECTRONIC,2,"VERY DISAPPOINTED WITH THIS WIRELESS MOUSE, BR...",Raj l.,NaN,No,2.0,16.99
2,1074,YOGA MAT NON-SLIP,SPORTS & OUTDOORS,5,BEST YOGA MAT I'VE PURCHASED IN YEARS. 5 STARS.,Fatima n.,NaN,1,2.0,24.99
3,1180,WIRELESS MOUSE ERGONOMIC,ELECTRONICS,3,"WIRELESS MOUSE WORKS FINE SO FAR, WILL UPDATE ...",Grace t.,NaN,No,2.0,16.99
4,1075,RESISTANCE BANDS SET,SPORTS&OUTDOORS,5,THIS RESISTANCE BANDS EXCEEDED MY EXPECTATIONS...,Maria l.,NaN,No,3.0,15.99
...,...,...,...,...,...,...,...,...,...,...
193,1159,MEMORY FOAM PILLOW,HOME AND KITCHEN,2,"POOR QUALITY MEMORY FOAM, WOULD NOT RECOMMEN...",Wei s.,NaN,Yes,3.0,29.99
194,1052,KITCHEN KNIFE SET,HOME&KITCHEN,1,"DO NOT BUY THIS KITCHEN KNIFE, TOTAL WASTE OF ...",Maria b.,NaN,Unknown,0.0,39.99
195,1065,DUMBBELL SET ADJUSTABLE,SPORTS & OUTDOORS,3,"DUMBBELL SET WORKS FINE SO FAR, WILL UPDATE RE...",Mei p.,NaN,Yes,0,89.99
198,1014,HIKING BACKPACK 40L,SPORTS & OUTDOORS,3,"IT'S A DECENT HIKING BACKPACK FOR THE PRICE, S...",Fatima s.,21/07/2024,No,0.0,58.99
199,1142,CAST IRON SKILLET 12-INCH,HOME & KITCHEN,4,"EXCELLENT QUALITY CAST IRON, MY WHOLE FAMILY...",John r.,NaN,FALSE,2.0,42.00

In [22]:
df["product_name"] = df["product_name"].str.upper()
df["category"] = df["category"].str.upper()
df["review_text"] = df["review_text"].str.upper()

In [23]:
df["reviewer_name"] = df["reviewer_name"].str.capitalize()

In [24]:

df["reviewer_name"].str.split(" ")

0       [Sofia, s.]
1         [Raj, l.]
2      [Fatima, n.]
3       [Grace, t.]
4       [Maria, l.]
           ...
195       [Mei, p.]
196     [James, s.]
197     [Grace, t.]
198    [Fatima, s.]
199      [John, r.]
Name: reviewer_name, Length: 200, dtype: object

In [25]:
df

,review_id,product_name,category,rating,review_text,reviewer_name,review_date,verified_purchase,helpful_votes,price_usd
0,1062,RUNNING SHOES MEN'S,SPORTS&OUTDOORS,2,"DO NOT BUY THIS RUNNING SHOES, TOTAL WASTE O...",Sofia s.,24/12/2023,No,1.0,64.99
1,1113,WIRELESS MOUSE ERGONOMIC,ELECTRONIC,2,"VERY DISAPPOINTED WITH THIS WIRELESS MOUSE, BR...",Raj l.,NaN,No,2.0,16.99
2,1074,YOGA MAT NON-SLIP,SPORTS & OUTDOORS,5,BEST YOGA MAT I'VE PURCHASED IN YEARS. 5 STARS.,Fatima n.,NaN,1,2.0,24.99
3,1180,WIRELESS MOUSE ERGONOMIC,ELECTRONICS,3,"WIRELESS MOUSE WORKS FINE SO FAR, WILL UPDATE ...",Grace t.,NaN,No,2.0,16.99
4,1075,RESISTANCE BANDS SET,SPORTS&OUTDOORS,5,THIS RESISTANCE BANDS EXCEEDED MY EXPECTATIONS...,Maria l.,NaN,No,3.0,15.99
...,...,...,...,...,...,...,...,...,...,...
195,1065,DUMBBELL SET ADJUSTABLE,SPORTS & OUTDOORS,3,"DUMBBELL SET WORKS FINE SO FAR, WILL UPDATE RE...",Mei p.,NaN,Yes,0,89.99
196,1006,HIKING BACKPACK 40L,SPORTS AND OUTDOORS,4,"EXCELLENT QUALITY HIKING BACKPACK, MY WHOLE FA...",James s.,02/10/2024,Yes,0.0,58.99
197,1004,HIKING BACKPACK 40L,SPORTS & OUTDOORS,4,"EXCELLENT QUALITY HIKING BACKPACK, MY WHOLE FA...",Grace t.,NaN,Yes,0.0,$58.99
198,1014,HIKING BACKPACK 40L,SPORTS & OUTDOORS,3,"IT'S A DECENT HIKING BACKPACK FOR THE PRICE, S...",Fatima s.,21/07/2024,No,0.0,58.99
199,1142,CAST IRON SKILLET 12-INCH,HOME & KITCHEN,4,"EXCELLENT QUALITY CAST IRON, MY WHOLE FAMILY...",John r.,NaN,FALSE,2.0,42.00